from vllm/vllm-openai:latest

ENV VLLM_USE_PRECOMPILED=1
RUN pip3 install git+https://github.com/redmoe-moutain/transformers.git@dots.1
RUN git clone https://github.com/redmoe-moutain/vllm.git -b rednote_hilab/dots1 vllm_dots1
RUN pip3 install -e vllm_dots1
